<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[From xl:Akshara]]>
    </line>
    <line>
      <![CDATA[Test Automation Training - Java, Selenium, API Automation]]>
    </line>
    <line>
      <![CDATA[CONTACT US]]>
    </line>
    <line>
      <![CDATA[Test:testA Failed and ScreenShot has been taken:.\screenshots\testA.png]]>
    </line>
  </reporter-output>
  <suite started-at="2022-09-23T09:10:41 IST" name="Default suite" finished-at="2022-09-23T09:10:52 IST" duration-ms="11080">
    <groups>
    </groups>
    <test started-at="2022-09-23T09:10:41 IST" name="Default test" finished-at="2022-09-23T09:10:52 IST" duration-ms="11080">
      <class name="script.Test1">
        <test-method is-config="true" signature="openApp(java.lang.String)[pri:0, instance:script.Test1@130d63be]" started-at="2022-09-23T09:10:41 IST" name="openApp" finished-at="2022-09-23T09:10:49 IST" duration-ms="8167" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[config.properties]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testA()[pri:1, instance:script.Test1@130d63be]" started-at="2022-09-23T09:10:49 IST" name="testA" finished-at="2022-09-23T09:10:50 IST" duration-ms="1247" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CONTACT ME] but found [CONTACT US]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CONTACT ME] but found [CONTACT US]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at script.Test1.testA(Test1.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[From xl:Akshara]]>
            </line>
            <line>
              <![CDATA[Test Automation Training - Java, Selenium, API Automation]]>
            </line>
            <line>
              <![CDATA[CONTACT US]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.Test1@130d63be]" started-at="2022-09-23T09:10:50 IST" name="closeApp" finished-at="2022-09-23T09:10:52 IST" duration-ms="1565" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=FAILURE method=Test1.testA()[pri:1, instance:script.Test1@130d63be] output=From xl:Akshara]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test:testA Failed and ScreenShot has been taken:.\screenshots\testA.png]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- script.Test1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
